⊟ [1 2] 3

≡⊟ [1 2 3] [4 5]

≡⊟ [1 2 3] []
≡(⊂⊂) [1 2 3] [4 5 6] []

∵⊟ [1 2 3] [4 5]

⊡ ↯0_2e [1]

Ex ~ "example"
Ex~RangeDiff

F! ← F!^!
F!+

regex "([a-z]" "hello world"

"Hello"_"Worrld"

⍜⊏() ⊚. [[0 0 1 0 0]
         [0 0 0 0 1]
         [1 0 0 0 0]
         [0 0 0 1 0]
         [0 1 0 0 0]]

[⋅⋅◌⍢(-1:0|>0)]1 "oops"

[⋅⋅◌⍢(-1:0|>0)]2 "ok"

[⋅◌ ⍥0] 1 "oops"

[⋅◌ ⍥0] 2 "ok"

F ← ⍣(
  ⊙◌°⊂ &p"Starts with 1" °(⊂1)
| &p"Starts with 2" °(⊂2)
| &p"Starts with 3" °(⊂3)
| &p"Starts with something else"∘
)
F [1]
